sudo: required

language: python

services:
  - docker

install:
  - docker run --name mysql-db -e MYSQL_ROOT_PASSWORD=password -d mysql:5.7
  - docker run --name mq-stock --hostname mq-host -d rabbitmq:3
  - docker run --name elastic -d elasticsearch

before_script:
  - docker build -t stock_tracer docker
  - docker run -d --link mysql-db:mysql --link mq-stock:rabbit --link elastic:elastic-host --name worker stock_tracer worker
  - docker ps
  - docker logs worker

script:
  - docker exec -t worker py.test -v 

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag stock_tracer ningy/stock_tracer:$TRAVIS_COMMIT;
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push ningy/stock_tracer:$TRAVIS_COMMIT;
    fi
