"""Add stocks table

Revision ID: 086b338432b2
Revises:
Create Date: 2016-06-14 13:49:28.928861

"""

# revision identifiers, used by Alembic.
revision = '086b338432b2'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(10), nullable=True),
    sa.Column('symbol', sa.String(10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stocks')
    ### end Alembic commands ###
