"""Inital DB

Revision ID: 3634dfdd77b0
Revises: 
Create Date: 2016-06-17 15:23:43.493067

"""

# revision identifiers, used by Alembic.
revision = '3634dfdd77b0'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('action_date', sa.DateTime(), nullable=False),
    sa.Column('in_progress', sa.Boolean(), nullable=True),
    sa.Column('interval_in_second', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stocks',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('stock_id'),
    sa.UniqueConstraint('exchange', 'symbol', name='stock_index')
    )
    op.create_table('quotes',
    sa.Column('quote_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('change', sa.Float(), nullable=False),
    sa.Column('change_percentage', sa.Float(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.stock_id'], ),
    sa.PrimaryKeyConstraint('quote_id'),
    sa.UniqueConstraint('stock_id', 'date', name='unique_stock_date')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    op.drop_table('stocks')
    op.drop_table('scheduled_actions')
    ### end Alembic commands ###
