"""add unique index for quote

Revision ID: 3c912bf1810a
Revises: 48da854caec3
Create Date: 2016-06-17 14:24:54.806704

"""

# revision identifiers, used by Alembic.
revision = '3c912bf1810a'
down_revision = '48da854caec3'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_stock_date', 'quotes', ['stock_id', 'date'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_stock_date', 'quotes', type_='unique')
    ### end Alembic commands ###
