"""Add last_udpate_time

Revision ID: 9be6e090bdab
Revises: 3634dfdd77b0
Create Date: 2016-08-04 15:16:34.868822

"""

# revision identifiers, used by Alembic.
revision = '9be6e090bdab'
down_revision = '3634dfdd77b0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scheduled_actions', sa.Column('last_update_time', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scheduled_actions', 'last_update_time')
    ### end Alembic commands ###
