db_base_url: mysql://root:password@mysql
db_name_ut: ut_stock
db_name_prod: stock

sleep_internal: 600 

mq_server: rabbit
mq_name: "stock_tracer"

es_host: elastic-host 

logging:
  file: true
  console: true
  es: true
